### signup user
POST http://localhost:3000/users/signup
content-type: application/json

{
    "email": "nylekersenjoseph@gmail.com",
    "password": "1234"
}

### sign in
POST http://localhost:3000/users/signin
content-type: application/json

{
    "email": "nyle8765@gmail.com",
    "password": "1234"
}

### test all users
GET http://localhost:3000/users

### get 1 user
GET http://localhost:3000/users/1

### get user connecté
GET http://localhost:3000/users/whoami

### deconexion d'un user
POST  http://localhost:3000/users/signout