### Signup User 1
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "firstName": "Manager",
  "lastName": "Test",
  "email": "manager@test.com",
  "password": "password123"
}

### Signup User 2
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "firstName": "Employee",
  "lastName": "Test",
  "email": "employee@test.com",
  "password": "password123"
}

### Login Manager
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "manager@test.com",
  "password": "password123"
}

### Login Employee
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "employee@test.com",
  "password": "password123"
}

### Tokens Stock
MANAGER_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoibWFuYWdlckB0ZXN0LmNvbSIsImVtcGxveWVlTnVtYmVyIjoiTUFOMTU4MzUiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc3NDk2NDc2MiwiZXhwIjoxNzc1MDUxMTYyfQ.rOWPjqLbRMBkflnMRg4DZiG3hlKzz3d-u4KDwvjKWJ4

### Approve User 2
PATCH http://localhost:3000/managers/users/2/approve
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoibWFuYWdlckB0ZXN0LmNvbSIsImVtcGxveWVlTnVtYmVyIjoiTUFOMTU4MzUiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc3NDk2NDc2MiwiZXhwIjoxNzc1MDUxMTYyfQ.rOWPjqLbRMBkflnMRg4DZiG3hlKzz3d-u4KDwvjKWJ4

### Set Employee
PATCH http://localhost:3000/managers/users/2/role-salary
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoibWFuYWdlckB0ZXN0LmNvbSIsImVtcGxveWVlTnVtYmVyIjoiTUFOMTU4MzUiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc3NDk2NDc2MiwiZXhwIjoxNzc1MDUxMTYyfQ.rOWPjqLbRMBkflnMRg4DZiG3hlKzz3d-u4KDwvjKWJ4
Content-Type: application/json

{
  "role": "EMPLOYEE",
  "hourlyRate": 20
}

### Get All Users with employee role (fails)
GET http://localhost:3000/managers/users
Authorization: Bearer EMPLOYEE_TOKEN

### Get All Users with manager role (works)
GET http://localhost:3000/managers/users
Authorization: Bearer MANAGER_TOKEN

### Set Availability for Employee
POST http://localhost:3000/employee/availability/2
Authorization: Bearer EMPLOYEE_TOKEN
Content-Type: application/json

{
  "dayOfWeek": "MONDAY",
  "isAvailable": true,
  "startTime": "09:00",
  "endTime": "17:00"
}

### Get Availability for Employee
GET http://localhost:3000/employee/availability/2
Authorization: Bearer EMPLOYEE_TOKEN

### Get Availability for Employee (Manager Access)
GET http://localhost:3000/employee/availability/2
Authorization: Bearer MANAGER_TOKEN

### update Availability for Employee
PATCH http://localhost:3000/employee/availability/1
Authorization: Bearer EMPLOYEE_TOKEN
Content-Type: application/json

{
  "dayOfWeek": "MONDAY",
  "isAvailable": true,
  "startTime": "09:00",
  "endTime": "17:00"
}

### Delete Availability for Employee
DELETE http://localhost:3000/employee/availability/1
Authorization: Bearer EMPLOYEE_TOKEN

