export enum NotificationType {
  ACCOUNT_CREATED = 'ACCOUNT_CREATED',
  ACCOUNT_APPROVED = 'ACCOUNT_APPROVED',

  LEAVE_REQUEST_PENDING = 'LEAVE_REQUEST_PENDING',
  LEAVE_REQUEST_APPROVED = 'LEAVE_REQUEST_APPROVED',
  LEAVE_REQUEST_REJECTED = 'LEAVE_REQUEST_REJECTED',
 
  SHIFT_EXCHANGE_ACCEPTED = 'SHIFT_EXCHANGE_ACCEPTED',
  SHIFT_EXCHANGE_REJECTED = 'SHIFT_EXCHANGE_REJECTED',
}