@baseUrl = http://localhost:3000
@tokenManager = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoibWFuYWdlckB0ZXN0LmNvbSIsImVtcGxveWVlTnVtYmVyIjoiTUFOMTU4MzUiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc3NTUyODk3MCwiZXhwIjoxNzc1NjE1MzcwfQ.uLmAsBRw91A85HJpviIiUWQxcl6trUk9y_EkwQm6OYQ
@tokenEmployee = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiZW1wbG95ZWVAdGVzdC5jb20iLCJlbXBsb3llZU51bWJlciI6IkVNUDk5MDA2Iiwicm9sZSI6ImFzc2lzdGFudF9tYW5hZ2VyIiwiaWF0IjoxNzc1NTI5MDQxLCJleHAiOjE3NzU2MTU0NDF9.aQ1x7vNOU4Z82n8cgUa29x3b5IAmEKsb7R7gM7vIg6k

### Signup Manager
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "firstName": "Manager",
  "lastName": "Test",
  "email": "manager@test.com",
  "password": "password123"
}

### Signup Employee
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "firstName": "Employee",
  "lastName": "Test",
  "email": "employee@test.com",
  "password": "password123"
}

### Login Manager
POST {{baseUrl}}/auth/signin
Content-Type: application/json

{
  "email": "manager@test.com",
  "password": "password123"
}

### Login Employee
POST {{baseUrl}}/auth/signin
Content-Type: application/json

{
  "email": "employee@test.com",
  "password": "password123"
}

### Refresh Token
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{tokenEmployee}}"
}

### Who Am I Employee
GET {{baseUrl}}/auth/whoami
Authorization: Bearer {{tokenEmployee}}

### Who Am I Manager
GET {{baseUrl}}/auth/whoami
Authorization: Bearer {{tokenManager}}

### Update Login Credentials
POST {{baseUrl}}/auth/update-login
Authorization: Bearer {{tokenManager}}
Content-Type: application/json

{
  "email": "new-email@test.com",
  "password": "newpassword123"
}

### Logout
POST {{baseUrl}}/auth/logout